### ISSUE TITLE
Add option to skip the dialogue

### ISSUE THREAD

**Issue by neilpate** [Bas-vE/LVDeleteFile#3]
It would be nice to be able to configure this tool so that it does not always prompt.

I would expect the vast majority of users are using SCC, so its not a big deal if you accidently delete.

I edited my local version for now to this and its now perfect!

![image](https://github.com/Bas-vE/LVDeleteFile/assets/7802334/d6d74401-66e3-41a1-8f1c-fea587f68756)

**Comment by Bas-vE** [comment]
I also got a PR from someone who changed the dialog to move to recycle bin or delete, and I do think this dialog should have a check mark to remember preferences, but still need to figure out where to make this option persistent and changeable if you want to swap functionality. Maybe something we can discuss this afternoon at the DutLUG

**Comment by Bas-vE** [comment]
Forgot to commit to this issue, but I added a checkbox to remember the choice of deletion in the last release

**Comment by neilpate** [comment]
Thanks @Bas-vE , I confirmed this does work.

Slightly unexpected implementation though.... ~~why the mouse stuff? Was this copied from a different example?~~ Sorry I understand now, this is not mouse button click, it is the position of button on the GUI. 

![image](https://github.com/Bas-vE/LVDeleteFile/assets/7802334/fc796597-8868-4890-a4a2-4c37e0a8018b)

**Comment by Bas-vE** [comment]
The PR I got used the 3 button dialog, which has this enum as output, so I replaced the dialog with my own and to add this functionality without changing that much about the move to recyclebin implementation I choose to keep using the enum in my ini file
